apiVersion: v1
kind: Service
metadata:
  labels:
    app: broker0
  name: broker0
  namespace: default
spec:
  # type: NodePort
  type: ClusterIP
  ports:
  - port: 10911
    targetPort: 10911
    name: broker-port
  selector:
    app: broker0
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: broker0
  namespace: default
spec:
  serviceName: broker0
  replicas: 1
  selector:
    matchLabels:
      app: broker0
  template:
    metadata:
     labels:
       app: broker0
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: broker0    
      # affinity:
      #   #podAntiAffinity 反亲合性
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       - labelSelector:
      #           matchExpressions:
      #           - key: "app"
      #             operator: In
      #             values:
      #               - broker0
      #         topologyKey: "kubernetes.io/hostname"
      #nodeSelector:
      #  topology.kubernetes.io/zone: eastus2-1      
      containers:
      - name: broker0
        image: apache/rocketmq:5.0.0
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0                
        env:
          - name: TZ
            value: Asia/Shanghai
          - name: NAMESRV_ADDR
            value: "mq-ns-0.default.svc.cluster.local:9876;mq-ns-1.default.svc.cluster.local:9876;mq-ns-2.default.svc.cluster.local:9876"
          - name: JAVA_OPT_EXT
            value: "-Duser.home=/home/rocketmq -Xms512M -Xmx512M -Xmn128m"
        command: ["sh","-c","./mqbroker -c /home/broker.conf"]
        volumeMounts:
          - name: rocketmq-data
            mountPath: /home/rocketmq/logs
          - name: rocketmq-data
            mountPath: /home/rocketmq/store
          - name: broker-config
            mountPath: /home/broker.conf
            subPath: broker.conf
        readinessProbe:
          tcpSocket:
            port: 10911
          initialDelaySeconds: 15
          timeoutSeconds: 5
          periodSeconds: 20
      volumes:
      - name: broker-config
        configMap:
          name: broker0
      #启动依赖
      initContainers:
      - name: init-mq-ns
        image: busybox:latest
        command: ['sh', '-c', "until nslookup mq-ns-0.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mq-ns; sleep 2; done"]

  volumeClaimTemplates:
  - metadata:
      name: rocketmq-data
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: "managed-csi"
      resources:
        requests:
          storage: 10Gi
